# Generated by detroit
# See https://github.com/bourbonut/detroit/tree/main/api_maker

from functools import partial
from operator import is_not

class project:
    def __init__(self, content="project"):
        self.content = content

    def __repr__(self):
        return self.content

    def __str__(self):
        return self.content

    def __call__(self, *args):
        arguments = ", ".join(map(repr, args))
        return f"{self}({arguments})"

    def invert(self, x=None, y=None):
        """
        The inverse of project.

        See more informations `here <https://d3js.org/d3-geo/projection#project_invert>`_.
        """
        arguments = ", ".join(map(repr, filter(partial(is_not, None), (x, y))))
        return project(content=f"{self.content}.invert({arguments})")

