# Generated by detroit
# See https://github.com/bourbonut/detroit/tree/main/api_maker

from functools import partial, update_wrapper
from operator import is_not{% for name, args, format_args, docstring in subclasses %}
from .{{ name.replace("d3.", "").replace("new ", "").replace("select", "_select") }} import {{ name.replace("d3.", "").replace("new ", "").replace("bin", "_bin") }}{% endfor %}

class ReprWrapper:
    """
    Wrapper class to make possible to represent methods in a different way
    """
    def __init__(self, repr, func):
        self._repr = repr
        self._func = func
        update_wrapper(self, func)

    def __call__(self, *args, **kw):
        return self._func(*args, **kw)
    def __repr__(self):
        return self._repr(self._func)

def repr_wrapper(func):
    return ReprWrapper(lambda method: f"d3.{method.__name__}", func)

class d3:
    """
    Class used to mimick javascript syntax for :code:`d3`

    See `documentation <https://d3js.org/getting-started>`_.

    Examples
    --------

    >>> from detroit import d3, js
    >>> d3.axisBottom(js("x")).tickFormat(d3.format(".0f"))
    d3.axisBottom(x).tickFormat(d3.format('.0f'))
    """
    def __init__(self, content="d3"):
        self.content = content

    def __repr__(self):
        return self.content

    def __str__(self):
        return self.content

    def __call__(self, *args):
        arguments = ", ".join(map(repr, args))
        return f"{self}({arguments})"
{% for name, args, format_args, docstring in methods %}
    @staticmethod{% if "scheme" in name or "interpolate" in name %}
    @repr_wrapper{% endif %}
    def {{ name.replace("d3.", "").replace("new ", "") }}({{ args }}):
        """
        {{ docstring }}
        """{% if format_args %}
        arguments = ", ".join(map(repr, filter(partial(is_not, None), {{ format_args }})))
        return d3(f"{{ name }}({arguments})")
{% else %}
        return d3("{{ name }}()")
{% endif %}{% endfor %}
{% for name, args, format_args, docstring in subclasses %}
    @staticmethod
    def {{ name.replace("d3.", "").replace("new ", "") }}({{ args }}):
        """
        {{ docstring }}
        """{% if format_args %}
        arguments = ", ".join(map(repr, filter(partial(is_not, None), {{ format_args }})))
        return {{ name.replace("d3.", "").replace("new ", "").replace("bin", "_bin") }}(f"{{ name }}({arguments})"){% else %}
        return {{ name.replace("d3.", "").replace("new ", "") }}("{{ name }}()"){% endif %}
{% endfor %}
svg = selection(content="svg")
